apiVersion: apps/v1
kind: Deployment
metadata: 
  name: traffic-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: traffic-backend
  template:
    metadata:
      labels:
        app: traffic-backend
    spec:
      containers:
      - name: backend
        image: python:3.9-slim  # Použijeme čistý Python image
        command: ["python", "-m", "http.server", "80"]
        ports:
        - containerPort: 80
        env:
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: REDIS_HOST
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: redis-password 

